create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table session(
    id bigint auto_increment not null,
    title varchar(255) not null,
    session_start timestamp not null,
    session_end timestamp,
    image_size bigint,
    image_width bigint,
    image_height bigint,
    image_type varchar(255),
    session_status varchar(255),
    course_id bigint not null,
    max_capacity bigint,
    fee bigint,
    primary key (id),
    constraint fk_course
            foreign key (course_id) references course(id)
);

create table session_student(
    session_id bigint not null,
    student_id bigint not null,
    primary key (session_id, student_id),
    foreign key (session_id) references session(id) on delete cascade,
    foreign key (student_id) references ns_user(id) on delete cascade
);
